"""possibilita exclusao de pedido

Revision ID: 537e4f683433
Revises: b12c0d6eb17c
Create Date: 2025-05-25 14:57:16.054824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '537e4f683433'
down_revision: Union[str, None] = 'b12c0d6eb17c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('order_product_order_id_fkey'), 'order_product', type_='foreignkey')
    op.create_foreign_key(None, 'order_product', 'order', ['order_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_product', type_='foreignkey')
    op.create_foreign_key(op.f('order_product_order_id_fkey'), 'order_product', 'order', ['order_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###
