"""cria tabela product

Revision ID: 5f54f8f4c378
Revises: 30124d5b278b
Create Date: 2025-05-24 10:47:17.987416

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5f54f8f4c378"
down_revision: Union[str, None] = "30124d5b278b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("value", sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column("bar_code", sa.String(), nullable=False),
        sa.Column("stock", sa.Integer(), nullable=False),
        sa.Column("expiration_date", sa.Date(), nullable=True),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.CheckConstraint("stock >= 0", name="stock_gte"),
        sa.CheckConstraint("value >= 0", name="value_gte"),
        sa.ForeignKeyConstraint(["category_id"], ["category.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_product_category_id"), "product", ["category_id"], unique=False
    )
    op.create_index(op.f("ix_product_stock"), "product", ["stock"], unique=False)
    op.create_index(op.f("ix_product_value"), "product", ["value"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_product_value"), table_name="product")
    op.drop_index(op.f("ix_product_stock"), table_name="product")
    op.drop_index(op.f("ix_product_category_id"), table_name="product")
    op.drop_table("product")
    # ### end Alembic commands ###
