"""insere coluna valor total em pedido

Revision ID: b12c0d6eb17c
Revises: fd11c6184982
Create Date: 2025-05-25 04:40:52.379303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b12c0d6eb17c'
down_revision: Union[str, None] = 'fd11c6184982'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('price_total', sa.DECIMAL(precision=10, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'price_total')
    # ### end Alembic commands ###
