services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    container_name: lu-api-dev
    command: bash -c "alembic upgrade head && gunicorn -w 4 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 main:app --reload"
    ports:
      - "8000:8000" 
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - db
    networks:
      - lu-network

  db:
    container_name: lu-db-dev
    image: postgres:17-alpine
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - lu_postgres_data_dev:/var/lib/postgresql/data/
    networks:
      - lu-network

volumes:
  lu_postgres_data_dev:

networks:
  lu-network:
    driver: bridge
